name = "echo_server"
version = "0.1.0"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
# description = ""
# licences = ["Apache-2.0"]
# repository = { type = "github", user = "username", repo = "project" }
# links = [{ title = "Website", href = "https://gleam.run" }]

[dependencies]
gleam_stdlib = ">= 0.59.0 and < 1.0.0"
glisten = { path = "../../" }
gleam_erlang = ">= 1.0.0 and < 2.0.0"
gleam_otp = { git = "https://github.com/gleam-lang/otp", ref = "factory-supervisor" }
logging = ">= 1.3.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
