name = "glisten"
version = "0.6.6"
description = "a shiny Gleam TCP/SSL server"
licences = ["Apache-2.0"]
repository = { type = "github", user = "rawhat", repo = "glisten" }

[dependencies]
gleam_stdlib = "~> 0.22"
gleam_otp = "~> 0.5"
gleam_erlang = "~> 0.15"

[dev-dependencies]
gleeunit = "~> 0.6"
