name = "glisten"
version = "0.11.0"
description = "a shiny Gleam TCP/SSL server"
licences = ["Apache-2.0"]
repository = { type = "github", user = "rawhat", repo = "glisten" }
gleam = ">= 0.32.0"

[dependencies]
gleam_stdlib = "~> 0.35 or ~> 1.0"
gleam_otp = "~> 0.9"
gleam_erlang = "~> 0.24"

[dev-dependencies]
gleeunit = "~> 1.0"
