name = "glisten"
version = "0.1.3"
description = "a shiny gleam webserver"
licences = ["Apache-2.0"]

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
# licences = ["Apache-2.0"]
# description = "A Gleam library..."
# repository = { type = "github", user = "username", repo = "project" }
# links = [{ title = "Website", href = "https://gleam.run" }]

[dependencies]
gleam_stdlib = "~> 0.20"
gleam_otp = "~> 0.4"
gleam_http = "~> 3.0"

[dev-dependencies]
gleeunit = "~> 0.6"
