name = "glisten"
version = "0.5.1"
description = "a shiny Gleam TCP server"
licences = ["Apache-2.0"]
repository = { type = "github", user = "rawhat", repo = "glisten" }

[dependencies]
gleam_stdlib = "~> 0.22"
gleam_otp = "~> 0.5"
gleam_http = "~> 3.1"
gleam_erlang = "~> 0.15"

[dev-dependencies]
gleeunit = "~> 0.6"
